version: 2
jobs:
  build:
    docker:
      - image: circleci/node:ltsworking_directory
    working_directory: frontend
    steps:
      - checkout
      - run: npm i
      - run: npm run build
  test:
    docker:
      - image: circleci/node:lts
    working_directory: frontend
    steps:
      - checkout
      - run: npm i
      - run: npm run test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
